### ISSUE TITLE
Refactoring Code

### ISSUE THREAD

**Issue by lukruh** [telebotter/mensabot#2]
Bis der Bot mit den neuen Klassen am laufen ist, dann kann munter vom master gebrancht werden, ohne dass jeder mit ner nicht funktionierenden Version arbeitet.

**Comment by hendricokakiko** [comment]
versteh nicht ganz was du willst, ist das issue jetzt closed?

**Comment by lukruh** [comment]
Test Antwort vom Handy via email

**Comment by hendricokakiko** [comment]
wow, das hjilft

**Comment by lukruh** [comment]
jo is closed
