### ISSUE TITLE
hey we also got a mensa bot :)

### ISSUE THREAD

**Issue by cvzi** [telebotter/mensabot#44]
Hey, I saw you left feedback in [our bot](https://telegram.me/OpenMensaRobot) :)
I did just publish our source: https://github.com/cvzi/openmensabot So please take a look if you like.
The code is really really hackish because we did only plan this to be a script for our daily mensa menu, but it turned out to become a "complete" bot for openmensa.

**Comment by lukruh** [comment]
i'll go for it and check it out, when i got some time.. thanks for the hint
