### ISSUE TITLE
Uhrzeit eingabe erleichtern

### ISSUE THREAD

**Issue by lukruh** [telebotter/mensabot#5]
Die Interpretation der Uhrzeit könnte etwas "intelligenter" laufen, wenigstens 09:00 Schreibweise sollte erkannt werden.

**Comment by hendricokakiko** [comment]
jo, hab auch schon bei mehreren leute gesehen wie das MEHRFACH hintereinander falsch interpretiert wir, selbst wenn ich sage 'tippe slash abo leerzeichen stunde stunde minute minute'

**Comment by lukruh** [comment]
doppelpunkt ist drin.. aber etwas ungeil implementiert, ne liste von formatstrings wäre eleganter

**Comment by lukruh** [comment]
HHMM, HH:MM, HH MM bisher supported

**Comment by lukruh** [comment]
für mich reicht das erstmal oder? wers immernoch nicht schafft ist zu dumm und muss es lernen
