### ISSUE TITLE
Mehrfach Abojobs

### ISSUE THREAD

**Issue by hendricokakiko** [telebotter/mensabot#6]

**Comment by lukruh** [comment]
hast du mal in die datenbank geschaut, ob er iwie 2 einträge bekommen hat? falls ja -> chat_id spalte in der datenbank als "primary" markieren.. ansonsten bot mal restarted? Tritt der Fehler dann immernoch auf?

**Comment by hendricokakiko** [comment]
fixed, es musste beim erstellen eines neuen abojobs der alte gelöscht werden. wurde vorher nicht gelöscht weil nur aktiviert wurde, nicht deklariert
